db_host = "localhost"
db_username = "limo"
db_password = "22360010s"
db_name = "limo" 

MPESA_CONSUMER_KEY='ecCg88qnyfE9OGEaGbFraZPDXrVJQ4yw1FUsShyKXT3QGwmJ'
MPESA_CONSUMER_SECRET='iZhGGbeLjNCob3ceHXoIwpTHYhLkpYTIrGU8bCl7cy4A0KRw3Ghm6ZAevKTHLDe7'
MPESA_BUSINESS_SHORT_CODE=174379
MPESA_PASSKEY='bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"'